# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email + SMS')], default='EMAIL', max_length=5)),
                ('audience', models.CharField(choices=[('ALL', 'All Parents'), ('CLASS', 'Specific Class'), ('BOARDERS', 'Hostel Boarders Only'), ('DEBTORS', 'Parents with Unpaid Fees'), ('CUSTOM', 'Custom Selection')], default='ALL', max_length=10)),
                ('subject', models.CharField(help_text='Email subject (auto-filled from template if used)', max_length=300)),
                ('body_email', models.TextField(blank=True, help_text='HTML email body')),
                ('body_sms', models.CharField(blank=True, help_text='SMS message (max 800 chars)', max_length=800)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Leave blank to send immediately', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('sms_sent', models.PositiveIntegerField(default=0)),
                ('sms_failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=5)),
                ('recipient', models.CharField(help_text='Email address or phone number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('OPTED_OUT', 'Opted Out')], default='PENDING', max_length=10)),
                ('provider_ref', models.CharField(blank=True, help_text='Message ID from email/SMS provider', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('FEE', 'Fee Reminder'), ('HOSTEL', 'Hostel Notice'), ('EXAM', 'Exam / Result'), ('GENERAL', 'General Announcement'), ('ATTENDANCE', 'Attendance Alert'), ('EMERGENCY', 'Emergency'), ('WELCOME', 'Welcome / Admission'), ('CUSTOM', 'Custom')], default='GENERAL', max_length=12)),
                ('subject', models.CharField(help_text='Email subject. Can use {{student_name}}, {{school_name}}, {{balance}}, etc.', max_length=300)),
                ('body_email', models.TextField(help_text='HTML email body. Placeholders: {{student_name}}, {{parent_name}}, {{class_name}}, {{balance}}, {{school_name}}, {{term}}, {{session}}')),
                ('body_sms', models.CharField(help_text='SMS body (max ~5 parts = 800 chars). Same placeholders available.', max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('ALL', 'All Channels')], max_length=5)),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Email + SMS')], max_length=5)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=7)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
