# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0002_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='childbilling',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_billings', to='users.student'),
        ),
        migrations.AddField(
            model_name='childbilling',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='childpaymentallocation',
            name='child_billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.childbilling'),
        ),
        migrations.AddField(
            model_name='childpaymentallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='users.student'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.class'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academics.term'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='installment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term'),
        ),
        migrations.AddField(
            model_name='installment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentbilling',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='parentbilling',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentbilling',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term'),
        ),
        migrations.AddField(
            model_name='childbilling',
            name='parent_billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.parentbilling'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='childpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='users.student'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='schoolitem',
            name='assigned_student',
            field=models.ForeignKey(blank=True, help_text='Assign this item to ONE specific student only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='users.student'),
        ),
        migrations.AddField(
            model_name='schoolitem',
            name='inventory_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_items', to='inventory.asset'),
        ),
        migrations.AddField(
            model_name='schoolitem',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Leave blank = available to all classes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.class'),
        ),
        migrations.AddField(
            model_name='schoolitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.schoolitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='school_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.schoolitem'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.student'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='parentbilling',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='installment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='childbilling',
            unique_together={('student', 'parent_billing')},
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.AlterUniqueTogether(
            name='parentbilling',
            unique_together={('wallet', 'session', 'term')},
        ),
    ]
