# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
import tenants.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible on public pricing page')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, help_text='Full annual price (discount already applied)', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('max_students', models.PositiveIntegerField(default=200)),
                ('max_staff', models.PositiveIntegerField(default=20)),
                ('max_classes', models.PositiveIntegerField(default=10)),
                ('feature_academics', models.BooleanField(default=True)),
                ('feature_cbt', models.BooleanField(default=False)),
                ('feature_results', models.BooleanField(default=True)),
                ('feature_finance', models.BooleanField(default=False)),
                ('feature_payroll', models.BooleanField(default=False)),
                ('feature_hostel', models.BooleanField(default=False)),
                ('feature_communications', models.BooleanField(default=False)),
                ('feature_inventory', models.BooleanField(default=False)),
                ('feature_timetable', models.BooleanField(default=False)),
                ('feature_announcements', models.BooleanField(default=True)),
                ('feature_parent_portal', models.BooleanField(default=True)),
                ('feature_api_access', models.BooleanField(default=False)),
                ('feature_custom_domain', models.BooleanField(default=False)),
                ('highlight_label', models.CharField(blank=True, help_text="e.g. 'Most Popular'", max_length=40)),
                ('highlight_color', models.CharField(blank=True, default='#d4a843', help_text='Hex colour for the highlight badge', max_length=7)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('renews_at', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_ref', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('paystack_ref', models.CharField(max_length=120, unique=True)),
                ('paystack_data', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official school name, e.g. Sunshine Academy', max_length=255)),
                ('subdomain', models.CharField(help_text="Unique subdomain slug, e.g. 'sunshine'", max_length=50, unique=True, validators=[tenants.models._slug_validator])),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery / Primary School'), ('secondary', 'Secondary / High School'), ('tertiary', 'Tertiary / Polytechnic'), ('vocational', 'Vocational / Technical')], default='secondary', max_length=20)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain if on Enterprise plan, e.g. portal.sunshineacademy.edu.ng', max_length=253)),
                ('email', models.EmailField(help_text='Primary contact / billing email', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(default='Nigeria', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('owner_name', models.CharField(blank=True, help_text='Name of the person who registered the school', max_length=150)),
                ('owner_email', models.EmailField(blank=True, help_text='Email of the registrant (may differ from school email)', max_length=254)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('TRIAL', 'Free Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=60)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('term_system', models.CharField(choices=[('trimester', '3 Terms'), ('semester', '2 Semesters')], default='trimester', max_length=20)),
                ('paystack_subaccount_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery / Primary School'), ('secondary', 'Secondary / High School'), ('tertiary', 'Tertiary / Polytechnic'), ('vocational', 'Vocational / Technical')], default='secondary', max_length=20)),
                ('subdomain', models.CharField(max_length=50, validators=[tenants.models._slug_validator])),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('school_address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('desired_billing', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=8)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Approximate number of students')),
                ('message', models.TextField(blank=True, help_text="Anything else you'd like us to know")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desired_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
