# Generated by Django 5.2.7 on 2026-05-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_per_student_term',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per student per term (e.g. 2000 for Starter)', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='terms_per_session',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of terms per session (usually 3)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_per_student',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per student at time of billing', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of students billed for this period'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_annual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat annual price (discount already applied)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat monthly price (used if price_per_student_term=0)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('TERM', 'Per Term'), ('SESSION', 'Per Session (3 Terms)'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='TERM', max_length=8),
        ),
    ]
