# Generated by Django 5.2.7 on 2026-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_plan_price_per_student_term_plan_terms_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistration',
            name='desired_billing',
            field=models.CharField(choices=[('TERM', 'Per Term'), ('SESSION', 'Per Session (3 Terms)'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='TERM', max_length=8),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('TERM', 'Per Term'), ('SESSION', 'Per Session (3 Terms)'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='TERM', max_length=8),
        ),
    ]
