# Generated by Django 5.2.7 on 2026-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('term', models.CharField(blank=True, choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('audience', models.CharField(choices=[('students', 'Students'), ('parents', 'Parents'), ('both', 'Students & Parents')], default='both', max_length=10)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notify_parents', models.BooleanField(default=False, help_text='Send email/SMS to parents when this announcement is published')),
                ('notify_channel', models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email + SMS')], default='BOTH', help_text='Which channel to use for parent notifications', max_length=5)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
