# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='e.g. B1, Top Bunk, Bottom Bunk', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=12)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BoarderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('BOARDER', 'Full Boarder'), ('DAY', 'Day Student'), ('WEEKLY', 'Weekly Boarder')], default='DAY', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Currently Boarding'), ('CHECKED_OUT', 'Checked Out'), ('SUSPENDED', 'Suspended'), ('EXEAT', 'On Exeat / Leave')], default='ACTIVE', max_length=12)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_rel', models.CharField(blank=True, max_length=50, verbose_name='Relationship')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions / Allergies')),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('EXEAT', 'Exeat / Leave'), ('RETURN', 'Return from Leave'), ('SUSPENSION', 'Suspension')], max_length=12)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateTimeField(blank=True, help_text='For exeat / leave only', null=True)),
                ('actual_return', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('parent_consent', models.BooleanField(default=False, help_text='Parent confirmed this movement')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Ground Floor, 1st Floor', max_length=50)),
                ('floor_number', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['hostel', 'floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male (Boys)'), ('FEMALE', 'Female (Girls)'), ('MIXED', 'Mixed')], max_length=6)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, help_text='Physical location / block description', max_length=300)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Total beds (auto-calculated from rooms)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('meal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('laundry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostelNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelTermBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base hostel/accommodation fee', max_digits=14)),
                ('meal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('laundry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid'), ('WAIVED', 'Waived')], default='UNPAID', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session__name', 'term__name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('DISCIPLINARY', 'Disciplinary'), ('MEDICAL', 'Medical'), ('PROPERTY', 'Property Damage'), ('THEFT', 'Theft'), ('BULLYING', 'Bullying'), ('SAFETY', 'Safety Concern'), ('OTHER', 'Other')], max_length=14)),
                ('severity', models.CharField(choices=[('LOW', 'Low — Minor Issue'), ('MEDIUM', 'Medium — Requires Attention'), ('HIGH', 'High — Serious'), ('CRITICAL', 'Critical — Immediate Action Required')], default='LOW', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=14)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='MealAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=10)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('menu', models.CharField(help_text='What is served', max_length=300)),
                ('time', models.TimeField(help_text='Meal serving time')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('DORMITORY', 'Dormitory (Shared)'), ('DOUBLE', 'Double Room'), ('SINGLE', 'Single Room'), ('SUITE', 'Suite')], default='DORMITORY', max_length=12)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Maximum number of beds')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Full'), ('MAINTENANCE', 'Under Maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('has_ac', models.BooleanField(default=False, verbose_name='Has A/C')),
                ('has_bathroom', models.BooleanField(default=False, verbose_name='Has Attached Bathroom')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hostel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Guardian'), ('SIBLING', 'Sibling'), ('RELATIVE', 'Other Relative'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='PARENT', max_length=10)),
                ('purpose', models.CharField(max_length=300)),
                ('id_type', models.CharField(blank=True, help_text='Type of ID presented', max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('COMPLETED', 'Visit Completed')], default='PENDING', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
