# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0002_initial'),
        ('hostel', '0002_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boarderprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarder_profile', to='users.student'),
        ),
        migrations.AddField(
            model_name='boarderprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='hostel.boarderprofile'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='floor',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this hostel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_warden_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term'),
        ),
        migrations.AddField(
            model_name='hostelnotice',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='hostelnotice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelnotice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_billings', to='hostel.boarderprofile'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='finance_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_billings', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term'),
        ),
        migrations.AddField(
            model_name='hosteltermbilling',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='hostel.boarderprofile'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_attendance', to='hostel.boarderprofile'),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hostel.mealplan'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hostel.floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='hostel.boarderprofile'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('hostel', 'floor_number')},
        ),
        migrations.AlterUniqueTogether(
            name='hosteltermbilling',
            unique_together={('boarder', 'term', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('hostel', 'meal_type', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='mealattendance',
            unique_together={('boarder', 'meal_plan', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
