# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Computer Club"', max_length=100)),
                ('slot_type', models.CharField(choices=[('CLUB', 'Club / Extra-curricular'), ('ASSEMBLY', 'Assembly'), ('SPORT', 'Sport'), ('EXAM', 'Exam'), ('OTHER', 'Other')], default='CLUB', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, help_text='e.g. "ICT Lab"', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('applies_to_all_classes', models.BooleanField(default=True, help_text='If unchecked, only applies to the selected classes below')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1, help_text='How many times this subject appears per week for this class')),
            ],
            options={
                'ordering': ['school_class__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Period 1"', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order within a day')),
                ('is_break', models.BooleanField(default=False, help_text='Mark as break/lunch – skipped in generation')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "2024/2025 First Term"', max_length=100, unique=True)),
                ('active_days', models.JSONField(default=list, help_text='List of day codes, e.g. ["MON","TUE","WED","THU","FRI"]')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
            ],
            options={
                'ordering': ['school_class__name', 'day', 'time_slot__order'],
            },
        ),
        migrations.CreateModel(
            name='DayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('label', models.CharField(help_text='Short description, e.g. "Friday – Computer Club Day"', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional longer description shown to students/teachers')),
                ('lessons_end_time', models.TimeField(help_text='Time when regular lessons finish (e.g. 12:20 for Friday)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
