# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialslot',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Leave empty if applies to all classes', to='users.class'),
        ),
        migrations.AddField(
            model_name='specialslot',
            name='override',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_slots', to='timetable.dayoverride'),
        ),
        migrations.AddField(
            model_name='specialslot',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_special_slots', to='users.staff'),
        ),
        migrations.AddField(
            model_name='specialslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class'),
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignments', to='users.staff'),
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='timetableconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='timetableconfiguration',
            name='time_slots',
            field=models.ManyToManyField(blank=True, to='timetable.timeslot'),
        ),
        migrations.AddField(
            model_name='teachersubjectclass',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_classes', to='timetable.timetableconfiguration'),
        ),
        migrations.AddField(
            model_name='generatedtimetable',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_timetables', to='timetable.timetableconfiguration'),
        ),
        migrations.AddField(
            model_name='dayoverride',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='timetable.timetableconfiguration'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.generatedtimetable'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectclass',
            unique_together={('config', 'staff', 'subject', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='dayoverride',
            unique_together={('config', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('timetable', 'school_class', 'day', 'time_slot'), ('timetable', 'teacher', 'day', 'time_slot')},
        ),
    ]
