# Generated by Django 5.2.7 on 2026-05-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='term',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('tenant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('tenant', 'session', 'name')},
        ),
    ]
